### ISSUE TITLE
Is this project still active? (as there are several bugs)

### ISSUE THREAD

**Issue by leovinus2001** [magnific0/SGP4#1]
Hi, just built the project on a Mac (as this is the most recent SGP4 version it seems).
I see C++ coding errors, and SEGV crashes. While I can provide details, I wondered whether anyone is looking at this code?
Maybe y'all have moved on the SGP-whatever new version in which case pointers would be appreciated.?
if still active then I can file a few issues which could be fixed.
Cheers

**Comment by magnific0** [comment]
Hi, no it's not really maintained. Also please find the most recent code the website of Vallado as mentioned in the README. I just checked the website and it seems there was a release last year, so it is for sure newer than this repo.
